apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: kibana-config
  labels:
    app: kibana
data:
  kibana.yml: |-
    elasticsearch:
      hosts: ${ELASTICSEARCH_URL}
      username: ${ELASTICSEARCH_USER}
      password: ${ELASTICSEARCH_PASSWORD}
